server:
  port: 9200

spring:
  application:
    name: "jghan-config-server"
  profiles:
    active: native
    # active: git
  cloud:
    config:
      server:
        # native:
        #   search-locations:
          # - "/Users/linalee/jghan/04.0225/msa_day4_step01/configserver/src/main/resources/config"
          # - "classpath:/config"
          # search-locations: "file:///Users//eazybytes//Documents//config"
        git:
          uri: "hhttps://github.com/jghan-no1/eureka-client-config-server.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

eureka:
  instance:
    # lease-renewal-interval-in-seconds: 10
    # lease-expiration-duration-in-seconds: 30
    preferIpAddress: true
    # hostname: ${HOSTNAME}
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://team6-eureka-server:8761/eureka/