server:
  port: 8762

spring:
  application:
    name: "config-server-jghan"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      url: "http://team6-config-server:8762"
      server:
        native:
          search-locations:
          # - "/Users/linalee/jghan/04.0225/msa_day4_step01/configserver/src/main/resources/config"
          - "classpath:/config"
          # search-locations: "file:///Users//eazybytes//Documents//config"
        git:
          uri: "https://github.com/jghan-no1/eureka-client-config-server.git"
          search-locations:
          - /config
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
