---
server:
  port: 8762

spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      # activate:
      #   on-profile: native
      server:
        native:
          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/jghan-no1/config-repository.git"
          # search-paths: config
          default-label: main  ## git의 branch 이름
          # uri: "https://github.com/jghan-no1/eureka-client-config-server.git"
          # search-paths: src/main/resources/config
          # default-label: step4  ## git의 branch 이름
          timeout: 5
          # clone-on-start: true
          force-pull: true
          # fail-fast: true  ## git 얀걀 실패 시 빠르게 예외 발생

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"
