---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team6-config-server
  namespace: group1-team6
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: team6-config-server
  template:
    metadata:
      labels:
        app: team6-config-server
    spec:
      containers:
      - name: team6-config-server
        image: k8s-vga-worker1:5000/group1-team6-config-server
        imagePullPolicy: Always
        ports:
        - containerPort: 8762
---
apiVersion: v1
kind: Service
metadata:
  name: team6-config-server
  namespace: group1-team6
spec:
  selector:
    app: team6-config-server
  ports:
  - protocol: TCP
    port: 8762
    targetPort: 8762
    # nodePort: 30614
  type: ClusterIP
  # type: NodePort
